name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm run ghpages:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: ./